fmt clarify repo and syst msg
langningchen/OJ pull request #9
Opened 2024-07-26 12:35 UTC by PythonSmall-Q

fmt clarify repo and syst msg

Well, why is this repo in CYEZOI but install.bash is in langningchen

Who knows

这个PR修改了repo的名字和地址，之前cute cln转的时候没有改喵。看到了就跑过来写了个简单的PR。望各位大神通过一下喵

2024-07-26 12:36 UTC, PythonSmall-Q commented
I wonder anyone is bad enough to close this

2024-07-27 15:39 UTC, langningchen requested changes

2024-07-27 15:39 UTC, langningchen commented on Install.bash
> +echo "OJ  Copyright (C) 2024  CYEZOI"
This change should be reverted for the copyright should not be changed.

2024-07-28 02:08 UTC, PythonSmall-Q commented
@langningchen done

2024-07-29 06:11 UTC, langningchen approved these changes

2024-07-29 06:11 UTC, merged